### ISSUE TITLE
Why only one output function

### ISSUE THREAD

**Issue by yangke** [a0x77n/chucky-ng#6]
I tried the newest joern-project
Whatever function  I chose，I got only one(the query one) function in the list
the result are as follows：

```
Job (4/13): msn_command_from_string (1020974) - char * param_start [Variable]
Run job ([yes]/no/quit)? n
Job (5/13): msn_command_from_string (1020974) - MsnCommand * cmd [Variable]
Run job ([yes]/no/quit)? n
Job (6/13): msn_command_from_string (1020974) - strchr [Callee]
Run job ([yes]/no/quit)? y
  1  0.21009    msn_command_from_string         1020974     $RET
Job (7/13): msn_command_from_string (1020974) - g_strsplit_set [Callee]
Run job ([yes]/no/quit)? quit
```

I checked the problem and find that  it was caused by the only parameter function_id passed from chucky_engine to anomaly_score
in chucky_engine when calling  to anomaly_score
there are only one function.node_id passed

```
 def _anomaly_rating(self):
        command = "echo %d |" % (self.job.function.node_id)
```

**Comment by fabsx00** [comment]
Hi yangke,
yes, that correct. "msn_command_from_string (1020974) - strchr [Callee]" means "is there anything unusual about usage of the symbol 'strchr' in the function msn_command_from_string?" And the answer is "21% of neighbors check the return value". Seems correct.
fabs

**Comment by yangke** [comment]
Do you mean that it will only return the analysis result of the queried function(The function I give in command line)
and it won't provide the anomaly score list of it's neighbors(similar functions)

**Comment by fabsx00** [comment]
Yes. Before, the code also returned some scores for neighbors, but they were invalid because they were not calculated over the neighbors of the neighbor ;)

**Comment by yangke** [comment]
Oh,I see! I also stuck in this problem before(when running the previous version).
I agree with your opinion!
How about Chucky paper? Does that method have this problem?

**Comment by fabsx00** [comment]
No. As I've said already: what you're looking at here is a (as of yet not entirely complete) reimplementation of Chucky based on the new version of joern done by Alwin. It has nothing to do with the implementation used to generate the results for the paper.

**Comment by fabsx00** [comment]
Alwin is one of our students. I don't know if he's a fan ;)

**Comment by yangke** [comment]
I see.
